App 89/ios logs
welldone-software/react-native-notifications pull request #7
Opened 2021-02-16 10:30 UTC by atar9500

2021-02-17 09:17 UTC, DanielZiv-SF requested changes
please add rotation

2021-02-17 09:23 UTC, DanielZiv-SF commented
and please add an example file

2021-02-17 16:28 UTC, atar9500 commented
Example log file
[notifications_logs.txt](https://github.com/welldone-software/react-native-notifications/files/5997095/notifications_logs.txt)

2021-02-18 18:23 UTC, DanielZiv-SF commented on lib/ios/RNLogger.m
> +unsigned long long FILE_LIMIT = 15 * 1024 * 1000;
```suggestion
unsigned long long FILE_LIMIT = 6 * 1024 * 1000;
```
if after rotation we will send 2 files, then we should lower the max size (2 * 6 * 2)

2021-02-23 09:07 UTC, DanielZiv-SF approved these changes

2021-02-23 09:09 UTC, merged